name: Feature Request
description: To request new features for either AMP or one of its application modules.
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      Note that this is not for requesting support for new games/applications. To do this you should go to https://github.com/CubeCoders/AMPTemplates and first attempt to build a configuration yourself - otherwise you can request a template from that repo.
- type: checkboxes
  attributes:
    label: I confirm that
    options:
      - label: I have searched for an existing feature request matching the description.
        required: true
- type: textarea
  attributes:
    label: Feature Request
    description: Describe your request.
  validations:
    required: true
